In [1]:
print("Helloworld")

Helloworld


In [2]:
print("Line1")
print("Line2")

Line1
Line2


In [3]:
%history

print("Helloworld")
print("Line1")
print("Line2")
%history


In [4]:
# %load abc.py
print("Line1")
print("Line2")
print("Line3")

Line1
Line2
Line3


In [5]:
%run abc.py

Line1
Line2
Line3


In [6]:
%time print("ada")

ada
Wall time: 0 ns


**Python**

In [7]:
%time l1 = list(range(1,3000000))
print(l1[:10])

Wall time: 93 ms
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
%time [x+5 for x in l1][:10]

Wall time: 391 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [9]:
for i, e in list(enumerate(l1)):
    l1[i] = l1[i] + 5
l1[:10]    

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [10]:
for i, e in list(enumerate(l1)):
    l1[i] += 5
l1[:10]  

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [11]:
l1 = [[1,2,3],
     [4,5,6],
     [7,8,9]]

print("Before Adding 5")
print(l1)
print()
for ri, rd in list(enumerate(l1)):
    for ci, cd in list(enumerate(rd)):
        l1[ri][ci] += 5
print("After Adding 5")
print(l1)

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [12]:
l1 = [1,2,4]
l1 + 5

TypeError: can only concatenate list (not "int") to list

**Numpy**

In [13]:
def abc():print("pakistan") #python
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [14]:
#import numpy as *
import numpy as np

In [15]:
l = [1,3,2]
print(sum(l)) # python function
print(np.sum(l)) # Numpy function

6
6


In [16]:
l1 = np.arange(1,3000000)
%time l1 + 5

Wall time: 6 ms


array([      6,       7,       8, ..., 3000002, 3000003, 3000004])

In [17]:
l1 = np.arange(1,13)

print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

Diminsion: 1
Type: int32
Size: 12
Itemsize: 4
Shape: (12,)


A Multidimensional Array Object

In [18]:
# l1 = np.arange(1,13).reshape((4,3))
# l1 = np.arange(1,13).reshape((3,4))
# l1 = np.arange(1,13).reshape((2,6))
# l1 = np.arange(1,13).reshape((6,2))
# l1 = np.arange(1,13).reshape((12,1))

l1 = np.arange(1,13).reshape((2,-1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (2, 6)


In [24]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int32
Size: 27
Itemsize: 4
Shape: (3, 3, 3)


In [25]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
# l1[i,j,k]
# l1[slide, row, column]
# l1[2]
# l1[1,2]
#l1[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [26]:
l1[1][2][0]

16

In [27]:
l1 = np.array(['a','b','c'])
print(l1)
l1[[True,True,False]]

['a' 'b' 'c']


array(['a', 'b'], dtype='<U1')

In [28]:
l1 = np.arange(1,28).reshape((3,3,3))
l1[l1 % 3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [29]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print(l1[l1 % 3 == 0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [30]:
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
l1[(l1 % 3 == 0) & (l1 % 9 == 0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 9, 18, 27])

In [31]:
l1 = np.random.randn(3,3,3)

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1.16478055  1.55656563  1.99955206]
  [-0.37855026  0.74309127  0.10467354]
  [ 0.74866543 -1.51676042  0.24311239]]

 [[ 0.40690306 -0.53201984  0.60714897]
  [-0.77329703 -0.13915424  0.45198372]
  [-1.45448213 -0.70853414  0.89213723]]

 [[ 0.41581571 -0.49803563 -1.43719555]
  [ 1.04620032  0.416399    1.32251878]
  [ 0.23776574  0.27749415 -1.54413157]]]
Diminsion: 3
Type: float64
Size: 27
Itemsize: 8
Shape: (3, 3, 3)


In [32]:
l1 + 2
#l1 * 2
#l1 / 2
#l1 ** 2
#l1 ** 0.5
#l1 % 2

array([[[3.16478055, 3.55656563, 3.99955206],
        [1.62144974, 2.74309127, 2.10467354],
        [2.74866543, 0.48323958, 2.24311239]],

       [[2.40690306, 1.46798016, 2.60714897],
        [1.22670297, 1.86084576, 2.45198372],
        [0.54551787, 1.29146586, 2.89213723]],

       [[2.41581571, 1.50196437, 0.56280445],
        [3.04620032, 2.416399  , 3.32251878],
        [2.23776574, 2.27749415, 0.45586843]]])

**Creating ndarrays**

In [33]:
# Deep Copy(Always copy)
l = [1,2,3]

a = np.array(l)
b = np.array(a)

print(a is l) #False
print(b is a) #False

False
False


In [34]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#2

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [35]:
import numpy as np
a = np.array([1,2])
a.itemsize

4

In [36]:
import numpy as np

**Creating ndarrays**

In [169]:
a = np.array([1,3,4])
b = np.asarray([1,3,5])

In [38]:
a = np.arange(1,14)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

**Chaining**

In [39]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7  

In [40]:
C(B(A(1)))

19

In [41]:
A(B(C(1)))

19

In [42]:
#arange().reshape()
#np.ones
#np.ones_like
#np.zeros
#np.zeros_like
#np.full
#np.full_like
#np.empty
#np.empty_like

In [43]:
a = np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [44]:
b = np.reshape(a, (27,1))
b

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27]])

In [45]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9)
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [46]:
a.shape = (9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [47]:
a.shape

(9, 3)

In [48]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
np.zeros((a.shape[0], a.shape[1]))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
a.shape

(9, 3)

In [51]:
np.zeros((a.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.zeros(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [54]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [55]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [57]:
b = np.ones_like(a) * 5 # + 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [58]:
b = np.full((3,3), 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [59]:
b = np.full_like(a, 5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [60]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [61]:
np.full_like(a, dtype=a.dtype, fill_value=2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [62]:
np.full_like(a, dtype=np.float64, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [63]:
np.empty((3,9))

array([[2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]])

In [64]:
np.empty_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
np.full_like(a, 1) * np.nan

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [66]:
np.full(a.shape, np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [67]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [68]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Data Types for ndarrays**

In [69]:
a = np.array([1,3,4], dtype='int')
a.dtype

dtype('int32')

In [70]:
a = np.array([1,3,4], dtype=int)
a.dtype

dtype('int32')

In [71]:
a = np.array([1,3,4], dtype=np.int64)
a.dtype

dtype('int64')

In [72]:
a = np.array([1,3,4], dtype='i8')
a.dtype

dtype('int64')

In [73]:
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int64')

In [74]:
c = a.astype(np.int64)
c.dtype

dtype('int64')

**Boolen Operation**

In [75]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [76]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [77]:
print(a)
a[a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [78]:
print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [79]:
print(a)
a[~a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [80]:
print(a)
a[~(a%3==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [81]:
print(a)
a[a%3!=0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [82]:
a = np.arange(1,7).reshape((2,3,1))
a

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

**Fancy Slicing**

In [83]:
import numpy as np

In [84]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[1,2,0]]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [85]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)

print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
#a[[0,1,2],[0,1,2],]
a[[1,2,0]][:,[2,1,0]]
#a[[1,2,0]][:,[-1,0]]
#a[[1,2,0],:,::-1]
#a[::-1]
#a[:,::-1,:]

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]



array([[[25, 26, 27],
        [22, 23, 24],
        [19, 20, 21]],

       [[34, 35, 36],
        [31, 32, 33],
        [28, 29, 30]],

       [[16, 17, 18],
        [13, 14, 15],
        [10, 11, 12]]])

In [86]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.07446108 -0.45003202 -0.15427911  1.00558929]
 [ 0.49446247 -0.8903352   1.11582676  0.8491074 ]
 [ 0.6136027   0.80224972  1.095218    0.16941307]
 [-1.39624578  0.38936304  1.51343252  0.07626516]
 [-0.9026191   0.98454181 -0.44301213 -0.23190143]
 [-1.81436002 -0.876861    1.49825504 -1.60543264]]


In [87]:
names == "Qasim"

array([ True, False, False, False,  True, False])

In [88]:
data[[ True, False, False, False,  True, False]]

array([[-0.07446108, -0.45003202, -0.15427911,  1.00558929],
       [-0.9026191 ,  0.98454181, -0.44301213, -0.23190143]])

In [89]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")

print()
data[names=="Qasim"]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[-0.34586799 -0.64839143  0.45685798  0.27172487]
 [-0.32621844  1.65206348 -1.23735661  1.56528468]
 [-1.53728315 -0.5883304  -0.22163755  1.58498864]
 [ 0.71246631 -0.43512495 -0.34268034 -0.88556609]
 [-0.03852229 -0.29721382 -0.64403275  0.83863313]
 [ 0.01921433  1.81332202 -1.55957746 -2.20697473]]



array([[-0.34586799, -0.64839143,  0.45685798,  0.27172487],
       [-0.03852229, -0.29721382, -0.64403275,  0.83863313]])

In [90]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 1.20095045 -0.42631426 -0.73539729 -1.09773917]
 [-0.22092092 -0.25918431 -1.86173873  0.13966427]
 [-0.42840195  0.59637814 -0.44126866  0.01628828]
 [-0.400457    0.82366213 -0.18809134  1.94163675]
 [ 0.18595808  0.70501979 -1.58085057 -2.0535748 ]
 [ 0.36660233 -1.29890233 -0.6834853  -1.13444211]]


array([[ 1.20095045, -0.42631426, -0.73539729, -1.09773917],
       [-0.400457  ,  0.82366213, -0.18809134,  1.94163675],
       [ 0.18595808,  0.70501979, -1.58085057, -2.0535748 ]])

In [91]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names!="Qasim") |  (names!="Ali")]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 0.41971767 -0.18568396 -0.80146711  0.39540205]
 [-0.96482683  1.7706022  -0.06136924 -0.12276088]
 [ 1.43911725 -1.29324275 -0.51351012 -0.80874586]
 [ 0.1670418   1.60193929 -2.2274848  -0.74998172]
 [ 1.85651947 -0.27788328  0.78002598 -0.1336797 ]
 [ 1.10856392  0.84098037 -0.35716618  0.54308211]]


array([[ 0.41971767, -0.18568396, -0.80146711,  0.39540205],
       [-0.96482683,  1.7706022 , -0.06136924, -0.12276088],
       [ 1.43911725, -1.29324275, -0.51351012, -0.80874586],
       [ 0.1670418 ,  1.60193929, -2.2274848 , -0.74998172],
       [ 1.85651947, -0.27788328,  0.78002598, -0.1336797 ],
       [ 1.10856392,  0.84098037, -0.35716618,  0.54308211]])

In [92]:
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")][:,[0,-1]]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 1.6646304  -0.3576936  -1.63522802  1.05551787]
 [-1.60924394 -0.78098241 -0.78708958  0.5871258 ]
 [-0.79261338 -1.13045036  1.31741378  0.03348832]
 [-1.57270877  0.73310726 -1.20447597  1.14423294]
 [-1.08872321 -1.35780526 -1.17843528 -2.07749387]
 [ 0.03366872  0.33642065  1.5243384  -0.28831021]]


array([[ 1.6646304 ,  1.05551787],
       [-1.57270877,  1.14423294],
       [-1.08872321, -2.07749387]])

In [93]:
l = [1,3,5,3,5]
l[:3]
l[:3] = 5

TypeError: can only assign an iterable

In [94]:
l = [1,3,5,3,5]
l[:3]
l[0] = 5
l

[5, 3, 5, 3, 5]

In [95]:
l = np.array([1,3,5,3,5])
l[:3]
l[:3] = 5
l

array([5, 5, 5, 3, 5])

In [96]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(8):
    a[i] = i
print(a)    

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [97]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [98]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(a.shape[0]):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [99]:
a = np.arange(8*4).reshape((8,4))
print(a)

for i, _ in enumerate(a):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


**Transposing Arrays and Swapping Axes**

In [100]:
a = np.arange(4*3).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [101]:
a.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [102]:
a.T.T.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [103]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [104]:
a.transpose()

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [105]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a * b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[ 3,  8],
       [15, 24]])

In [106]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a @ b

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [107]:
a = np.array([[1,2],
             [3,4]])
b = a+2
print(a,b, sep="\n\n", end="\n\n")

a.dot(b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]



array([[13, 16],
       [29, 36]])

In [108]:
a.dot(a.T)

array([[ 5, 11],
       [11, 25]])

In [109]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.T

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [110]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
a.transpose(2,1,0)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [111]:
a = np.arange(3*3*3).reshape((3,3,3))
print(a)
#a.reshape(a.shape[2], a.shape[1])
a.swapaxes(2,1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 0,  3,  6],
        [ 1,  4,  7],
        [ 2,  5,  8]],

       [[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]],

       [[18, 21, 24],
        [19, 22, 25],
        [20, 23, 26]]])

**Table 4-3. Unary ufuncs**

In [112]:
a = np.array([7,8,-20,2,-3,20])
np.abs(a)

array([ 7,  8, 20,  2,  3, 20])

In [113]:
a = np.array([7,8,-20,2,-3,20])
np.fabs(a)

array([ 7.,  8., 20.,  2.,  3., 20.])

In [114]:
a = np.array([36,25,16])
np.fabs(a)

array([36., 25., 16.])

In [115]:
a = np.array([7,8,-20,2,-3,20])
np.square(a)

array([ 49,  64, 400,   4,   9, 400], dtype=int32)

In [116]:
np.exp(a)

array([1.09663316e+03, 2.98095799e+03, 2.06115362e-09, 7.38905610e+00,
       4.97870684e-02, 4.85165195e+08])

In [117]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.ceil(a)

array([3., 3., 3., 3.])

In [118]:
a = np.array([2.3, 2.1,2.9, 2.8])
np.floor(a)

array([2., 2., 2., 2.])

In [119]:
a = np.array([2.8, 9.7, 5.9])
for i in a:
    i = str(i).split(".")
    print(i[0], i[1])

2 8
9 7
5 9


In [120]:
a = np.array([2.8, 9.7, 5.9])
f, w = np.modf(a)
print(w,f, sep="\n")

[2. 9. 5.]
[0.8 0.7 0.9]


In [121]:
np.isnan(np.nan)

True

In [122]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.maximum(a,b)

array([3, 3, 5, 7])

In [123]:
np.fmax(a,b)

array([3, 3, 5, 7])

In [124]:
np.fmax??

**4.3 Array-Oriented Programming with Arrays**

In [125]:
a = np.arange(4*3)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [126]:
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

**Expressing Conditional Logic as Array Operations**
**np.wher(condition, value_true, value_false)**

In [127]:
a = np.arange(8*4).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [ ]:
#np.where(condition, True_block, False_block)

In [129]:
np.where(a%3 == 0, "Yes","No")

array([['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No'],
       ['No', 'Yes', 'No', 'No'],
       ['Yes', 'No', 'No', 'Yes'],
       ['No', 'No', 'Yes', 'No']], dtype='<U3')

In [130]:
a = np.array([1,3,5,7])
b = np.array([3,2,2,1])

np.where(a>b, a, b)

array([3, 3, 5, 7])

**Mathematical and Statistical Methods**

In [131]:
a = np.arange(3*4).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
np.sum(a)

66

In [133]:
print(a)
np.sum(a, axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [134]:
print(a)
np.sum(a, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

**Broad Casting**

In [135]:
a = np.arange(5*5).reshape((5,5))
print(a)
a + 5

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [136]:
a = np.arange(5*5).reshape((5,5))
b = np.full_like(a, 5)
print(a,b,sep="\n\n")
a + b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

**stacking**
**split**
**> Stacking**

In [137]:
import numpy as np
a = np.random.randint(1,10, size=10)
b = a + 5
print(a, b, sep='\n')
print(len(a),len(b))

[6 4 3 7 2 9 5 6 5 3]
[11  9  8 12  7 14 10 11 10  8]
10 10


In [138]:
print(a,b, sep='\n\n')

[6 4 3 7 2 9 5 6 5 3]

[11  9  8 12  7 14 10 11 10  8]


In [139]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=0)

[6 4 3 7 2 9 5 6 5 3]

[11  9  8 12  7 14 10 11 10  8]


array([[ 6,  4,  3,  7,  2,  9,  5,  6,  5,  3],
       [11,  9,  8, 12,  7, 14, 10, 11, 10,  8]])

In [140]:
print(a,b, sep='\n\n')
np.stack((a,b), axis=1)

[6 4 3 7 2 9 5 6 5 3]

[11  9  8 12  7 14 10 11 10  8]


array([[ 6, 11],
       [ 4,  9],
       [ 3,  8],
       [ 7, 12],
       [ 2,  7],
       [ 9, 14],
       [ 5, 10],
       [ 6, 11],
       [ 5, 10],
       [ 3,  8]])

In [141]:
# np.stack((a,b), axis=1)
np.column_stack((a,b))

array([[ 6, 11],
       [ 4,  9],
       [ 3,  8],
       [ 7, 12],
       [ 2,  7],
       [ 9, 14],
       [ 5, 10],
       [ 6, 11],
       [ 5, 10],
       [ 3,  8]])

In [142]:
np.stack((a,b), axis=0)

array([[ 6,  4,  3,  7,  2,  9,  5,  6,  5,  3],
       [11,  9,  8, 12,  7, 14, 10, 11, 10,  8]])

In [143]:
np.stack((a,b), axis=0)

array([[ 6,  4,  3,  7,  2,  9,  5,  6,  5,  3],
       [11,  9,  8, 12,  7, 14, 10, 11, 10,  8]])

In [144]:
# 
# 
np.row_stack((a,b))

array([[ 6,  4,  3,  7,  2,  9,  5,  6,  5,  3],
       [11,  9,  8, 12,  7, 14, 10, 11, 10,  8]])

In [145]:
np.hstack((a,b))

array([ 6,  4,  3,  7,  2,  9,  5,  6,  5,  3, 11,  9,  8, 12,  7, 14, 10,
       11, 10,  8])

In [146]:
np.vstack((a,b))

array([[ 6,  4,  3,  7,  2,  9,  5,  6,  5,  3],
       [11,  9,  8, 12,  7, 14, 10, 11, 10,  8]])

In [147]:
b = np.arange(3*3).reshape((3,3)) 
a = a + 5
print(a, b, sep='\n\n')

[11  9  8 12  7 14 10 11 10  8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [170]:
np.vstack((a,b))

array([[1, 3, 4],
       [1, 3, 5]])

In [171]:
np.hstack((a,b))

array([1, 3, 4, 1, 3, 5])

In [172]:
np.column_stack((a,b))

array([[1, 1],
       [3, 3],
       [4, 5]])

In [151]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.dstack((a,b))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[ 0,  1,  7,  8],
        [ 2,  3,  9, 10]],

       [[ 4,  5, 11, 12],
        [ 6,  7, 13, 14]]])

In [152]:
a = np.arange(2*2*2).reshape((2,2,2))
b = a + 7
print(a,b, sep='\n->SecondArray->\n')
np.stack((a,b), axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
->SecondArray->
[[[ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]]]


array([[[[ 0,  1],
         [ 7,  8]],

        [[ 2,  3],
         [ 9, 10]]],


       [[[ 4,  5],
         [11, 12]],

        [[ 6,  7],
         [13, 14]]]])

In [153]:
np.stack??

In [154]:
a.reshape((2,-1))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

**Split**

In [155]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=0)
np.split(a, 3, axis=0)
np.split(a, 2, axis=0)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [156]:
a = np.arange(6*6).reshape((6,6))
print(a)
np.split(a, 6, axis=1)
np.split(a, 3, axis=1)
np.split(a, 2, axis=1)[0]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]])

In [157]:
a = np.arange(2*2*2).reshape((2,2,2))
p=print(a)

np.dsplit(a, 2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]), array([[[1],
         [3]],
 
        [[5],
         [7]]])]

**Table 4-6. Array set operations**

In [158]:
a = np.random.randint(1,10, size=20)
print(a)
np.unique(a)

[7 4 3 5 5 1 8 1 2 9 2 9 1 2 9 7 1 5 3 7]


array([1, 2, 3, 4, 5, 7, 8, 9])

In [159]:
piaic = np.random.randint(1,100, size=30)
cnic = np.random.randint(1,10, size=5)
print(piaic, cnic,sep='\n\n')

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


In [160]:
[True if x in piaic else False for x in cnic]

[False, False, False, False, False]

In [161]:
[x in piaic for x in cnic]

[False, False, False, False, False]

In [162]:
["Yes" if x in piaic else "NO" for x in cnic]

['NO', 'NO', 'NO', 'NO', 'NO']

In [163]:
print(piaic, cnic,sep='\n\n')
np.in1d(cnic, piaic)

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


array([False, False, False, False, False])

In [164]:
print(piaic, cnic,sep='\n\n')
c = np.in1d(cnic, piaic)
np.where(c==True,"Yes","No")

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


array(['No', 'No', 'No', 'No', 'No'], dtype='<U3')

In [165]:
print(piaic, cnic,sep='\n\n')
np.intersect1d(cnic, piaic)

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


array([], dtype=int32)

In [166]:
print(piaic, cnic,sep='\n\n')
np.union1d(cnic, piaic)

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


array([ 1,  4,  5,  6,  7,  8,  9, 14, 16, 20, 24, 25, 29, 30, 31, 34, 38,
       42, 44, 52, 53, 60, 62, 63, 71, 74, 86, 87, 95, 98, 99])

In [167]:
print(piaic, cnic,sep='\n\n')
np.setdiff1d(cnic, piaic)

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


array([1, 5, 8, 9])

In [168]:
# XOR
# 0 0 -> 0
# 1 0 -> 1
# 0 1 -> 1
# 1 1 -> 0
print(piaic, cnic,sep='\n\n')
np.setxor1d(cnic, piaic)

[24 34 74 16 30 62 53 63 86 25 44 60 98  4 52 87  6 14 38 95 20 42 31  4
 31 31  7 71 99 29]

[9 8 5 1 9]


array([ 1,  4,  5,  6,  7,  8,  9, 14, 16, 20, 24, 25, 29, 30, 31, 34, 38,
       42, 44, 52, 53, 60, 62, 63, 71, 74, 86, 87, 95, 98, 99])