In [16]:
import numpy as np

In [17]:
np.__version__

'1.16.5'

In [18]:
!pip install --upgrade numpy

Requirement already up-to-date: numpy in c:\users\rimsh\anaconda3\lib\site-packages (1.21.5)


In [19]:
np.__version__

'1.16.5'

In [20]:
%time

Wall time: 0 ns


In [22]:
%run abc.py

I am from abc file


In [23]:
[i+5 for i in range(6000000)][:1000000]
%time

Wall time: 0 ns


In [24]:
a = np.arange(6000000) + 5
a[:1000000]
%time

Wall time: 0 ns


In [25]:
l = [[1,2,3],
    [4,5,6],
    [7,8,9]]
l 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
for i in enumerate(l):
    for c in enumerate(l[i[0]]):
        l[i[0]][c[0]] += 5
        

In [27]:
l

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]

**Solve Above taks with numpy**
**list to array**

In [28]:
l1 = np.array([1,2,3])
l1

array([1, 2, 3])

In [29]:
l1 = np.array((1,2,3))
l1

array([1, 2, 3])

In [30]:
l1 = np.array({1,2,3,4,2})
l1

array({1, 2, 3, 4}, dtype=object)

In [31]:
l2 = np.asarray([1,3,4])
l2

array([1, 3, 4])

In [32]:
l1 = np.arange(1,10)
l1 = l1.reshape((3,3))
l1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
l1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
l1 - 2


array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [35]:
l1[0,:] =+ 5

In [36]:
l1

array([[5, 5, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
l2 = np.arange(3*3*3*2).reshape((3,3,3,2))
l2

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]],


       [[[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53]]]])

In [38]:
type(l2)

numpy.ndarray